import js from '@eslint/js';

const names = [
  'window',
  'document',
  'navigator',
  'location',
  'performance',
  'matchMedia',
  'Audio',
  'AudioContext',
  'webkitAudioContext',
  'Image',
  'ImageData',
  'requestAnimationFrame',
  'cancelAnimationFrame',
  'addEventListener',
  'removeEventListener',
  'innerWidth',
  'innerHeight',
  'devicePixelRatio',
  'localStorage',
  'getComputedStyle',
  'setTimeout',
  'clearTimeout',
  'setInterval',
  'clearInterval',
  'console',
  'URL',
  'URLSearchParams',
  'fetch',
  'Blob',
  'Event',
  'CustomEvent',
  'ProgressEvent',
  'structuredClone',
  'EventTarget',
  'setImmediate',
  'process',
  'Buffer',
  '__RUNTIME_ASSET_PREFIX__',
];
export default [
  { ignores: ['dist/**', 'node_modules/**', 'output/**', 'local-archive/**', 'renders/**'] },
  {
    files: ['src/**/*.js', 'scripts/**/*.mjs', 'tests/**/*.{js,mjs}', '*.js', '*.mjs'],
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: Object.fromEntries(names.map((name) => [name, 'readonly'])),
    },
    rules: {
      ...js.configs.recommended.rules,
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none', ignoreRestSiblings: true }],
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
];
