export const CALF_RESCUE = Object.freeze({
  notice: 10,
  alert: 12,
  hear: 20,
  threat: 12,
  defense: 8,
  retreatProbability: 0.5,
  sprint: 3.1,
  follow: 2.6,
  sprintSeconds: 10,
  followSeconds: 10,
  flee: 3.8,
  carry: 1.6,
  walk: 2,
  grabSeconds: 0.6,
  dropSeconds: 0.6,
  bullSpeed: 5.5,
  bullWindup: 0.5,
  bullLimit: 16,
  cooldown: 30,
  flightSeconds: 1,
  flightHeight: 2,
  landingSeconds: 2,
});
